baseURL = "https://www.hidigital.solutions/"
languageCode = "en-us"
title = "HI Digital Solutions, LLC"
theme = "ananke"

sectionPagesMenu = "main"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
PygmentsCodeFences = true

[params]
  favicon = ""
  description = "Simple solutions to complex problems"
  twitter = "https://twitter.com/hids0"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/company/proactive-digital-insights"
  contactPhone = ""
  contactAddress = ""

# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  custom_css = ["css/hids.css","css/rouge-highlight.css"]
