baseURL = "https://hids.io/"
languageCode = "en-us"
title = "HI Digital Solutions" 
theme = "ananke"

sectionPagesMenu = "main"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  twitter = "https://twitter.com/hids_io"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"